version: "3.8"
services:
  server:
    build:
      context: .
    environment:
      - NODE_ENV=production
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
